server {
    listen 443 ssl;

    server_name aakherra.42.fr;

    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /adminer/ {
        include fastcgi_params;
        fastcgi_pass adminer:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
    }

    location /onlogs/ {
        proxy_pass http://onlogs:8798;
    }

    location /website/ {
        proxy_pass http://website:80/;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
